### ISSUE TITLE
Readme should avoid always showing uid strings, use friendly variable names instead.

### ISSUE THREAD

**Issue by cboettig** [sckott/rphylopic#15]
Completely minor thing: I think the readme would read more naturally if you began with a search for a species name, and stored the returned identifier in a semantically meaningful string ("cat", "bug"), to minimize showing the full hashes.  e.g.

```r
person <- name_search("Homo sapiens")[1,1]
image_data(person)
```

might be less intimidating.

**Comment by sckott** [comment]
good idea!
