### ISSUE TITLE
Error: Not Found (HTTP 404)

### ISSUE THREAD

**Issue by sghignone** [sckott/rphylopic#31]
HI!
I'm trying to work with images different from provided examples, but I keep getting the error in subject.
I'm interested in this pic: http://phylopic.org/name/ce1858b8-d072-4283-a985-ac06352d4ba9 (NameBank ID: 354593), so this is what I am doing:

> ubio_get(namebankID = **354593**)[[1]]
[1] "ce1858b8-d072-4283-a985-ac06352d4ba9"       (n.b, same as in db link)

> image_data("ce1858b8-d072-4283-a985-ac06352d4ba9", size = "512")
Error in png::readPNG(res$content) : libpng error: Not a PNG file

> image_get(uuid = "ce1858b8-d072-4283-a985-ac06352d4ba9")
Error: Not Found (HTTP 404)

> image_get(uuid = "ce1858b8-d072-4283-a985-ac06352d4ba9", options=c('credit','pngFiles','taxa','canonicalName','string','uri','type'))
Error: Not Found (HTTP 404)

...I'm just following your examples....where are my mistakes?
Thanks
s.-

**Comment by sckott** [comment]
thanks for opening an issue. 

unfortunately, its a bit confusing. there's uuids at many levels. `ubio_get` gets the UUID for the taxon, but you need to get the UUID for the image within the taxon. this should work:

```r
library(rphylopic)
library(ggplot2)
x <- ubio_get(namebankID = 354593)
z <- name_images(x$uid)
img <- image_data(z$same[[1]]$uid, size = "512")
qplot(x=Sepal.Length, y=Sepal.Width, data=iris, geom="point") +
  add_phylopic(img[[1]])
```

**Comment by sghignone** [comment]
got it! the id is referred to pic id!
